### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by dzmitry-lahoda** [TheAngryByrd/BenchmarkDotNet.Template#3]
Allow package `autodiscovery`. I.e. if package named `BenchmarkDotNet` than its template is `BenchmarkDotNet.Template`. See `Expecto` for example.

**Comment by TheAngryByrd** [comment]
Unfortunately `BenchmarkDotNet` is a reserved prefix and I cannot use it.  https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation
